// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProduksiMobilApp.Data;

#nullable disable

namespace ProduksiMobilApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProduksiMobilApp.Models.ProductionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FixJumat")
                        .HasColumnType("int");

                    b.Property<int>("FixKamis")
                        .HasColumnType("int");

                    b.Property<int>("FixMinggu")
                        .HasColumnType("int");

                    b.Property<int>("FixRabu")
                        .HasColumnType("int");

                    b.Property<int>("FixSabtu")
                        .HasColumnType("int");

                    b.Property<int>("FixSelasa")
                        .HasColumnType("int");

                    b.Property<int>("FixSenin")
                        .HasColumnType("int");

                    b.Property<int>("Jumat")
                        .HasColumnType("int");

                    b.Property<int>("Kamis")
                        .HasColumnType("int");

                    b.Property<int>("Minggu")
                        .HasColumnType("int");

                    b.Property<int>("Rabu")
                        .HasColumnType("int");

                    b.Property<int>("Sabtu")
                        .HasColumnType("int");

                    b.Property<int>("Selasa")
                        .HasColumnType("int");

                    b.Property<int>("Senin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductionPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
